defaults:
  - algo: null
  - _self_

save_topk: 5
total_queries: 500
objective_metric: "VAL_PGD_ACC"
objective_direction: max

seed: 42

hydra:
  run:
    dir: outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: multirun/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${sanitize_dirname:${hydra.job.override_dirname}}
  verbose: false